apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-grpc-staging
    extratag: %{SUBSTITUTED_ARGUMENT}
  name: hello-grpc-staging
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: hello-grpc-staging
  type: LoadBalancer
