apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: image-stamping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-stamping
    spec:
      containers:
      - name: image-stamping
        image: index.docker.io/parsec86/{REPOSITORY}:{STABLE_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 50051 
