apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-controller-staging
  annotations:
    rules-k8s.bazel.io/foo: |
      ---
      foo: bar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-controller-staging
    spec:
      containers:
      - name: todo-controller
        image: us.gcr.io/not-my-project/todo-controller:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
