apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-http-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-http-staging
    spec:
      containers:
      - name: hello-http
        image: hello-http-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
